In [ ]:
!pip install pandas
!pip install seaborn

# meload dataset

In [13]:
import pandas as pd
data = pd.read_csv("./dataset.csv")

# menampilkan dataset

In [38]:
data

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,4,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,4,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,2,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,3,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,3,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,4,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,4,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,4,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,2,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,3,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

# analisis: jumlah pembeli pria dan wanita

In [ ]:
gender_counts = data['Gender'].value_counts()
print(gender_counts)

# analisis: barang yang paling suka dibeli oleh pria atau wanita

In [ ]:
most_purchased_items = data.groupby(['Gender', 'Item Purchased']).size().reset_index(name='Count')
most_purchased_items = most_purchased_items.sort_values(by='Count', ascending=False).groupby('Gender').head(1).reset_index(drop=True)
print(most_purchased_items)

# visualisasi: jumlah pembelian oleh pria dan wanita

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Count the number of males and females
gender_counts = data['Gender'].value_counts()

# Create a bar plot
sns.barplot(x=gender_counts.index, y=gender_counts.values)
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('Comparison of Men and Women')
plt.show()

# visualisasi: most bought items

In [ ]:
import seaborn as sns

most_bought_items = data['Item Purchased'].value_counts().reset_index()
most_bought_items.columns = ['Item Purchased', 'Count']

# Create a bar plot
sns.barplot(x='Item Purchased', y='Count', data=most_bought_items)
plt.xlabel('Item Purchased')
plt.ylabel('Count')
plt.title('Most Bought Items')
plt.xticks(rotation=90)
plt.show()

# analisis: korelasi pearson antara musim dan rating

In [ ]:
correlation = data['Purchase Amount (USD)'].corr(data['Review Rating'])
print(f"Pearson correlation between Purchase Amount (USD) and Review Rating: {correlation}")

# Transormasi data kategorical menjadi data numeral

In [ ]:
# Define a mapping for sizes
size_mapping = {'XS': 1, 'S': 2, 'M': 3, 'L': 4, 'XL': 5}

# Apply the mapping to the Size column
data['Size'] = data['Size'].map(size_mapping)

# Display the updated dataframe
data.head()

# Analisis: Apakah Ukuran benda Clothing yang dibeli, berkolerasi dengan rating

In [ ]:
# Filter the data for the "Clothing" category
clothing_data = data[data['Category'] == 'Clothing'] # mengandung hanya data baju

# Calculate the correlation between review rating and size
clothing_correlation = clothing_data['Review Rating'].corr(clothing_data['Size'])
print(f"Correlation between Review Rating and Size for Clothing: {clothing_correlation}")